"""Add progress column to Video model

Revision ID: 3a009f101771
Revises: 5bb243a32685
Create Date: 2025-11-08 15:52:42.074850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a009f101771'
down_revision: Union[str, Sequence[str], None] = '5bb243a32685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('progress', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'progress')
    # ### end Alembic commands ###
