"""Widen status column in videos table

Revision ID: 449e6d1a87a2
Revises: 3a009f101771
Create Date: 2025-11-08 16:30:57.643193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '449e6d1a87a2'
down_revision: Union[str, Sequence[str], None] = '3a009f101771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'status',
               existing_type=mysql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED'),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'status',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED'),
               existing_nullable=False)
    # ### end Alembic commands ###
